# fly.toml app configuration file generated for yt-downloader-withered-forest-3825 on 2025-07-22T19:23:15+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'yt-downloader-withered-forest-3825'
primary_region = 'fra'

[build]

[processes]
  app = "python main.py"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
